GET http://localhost:5000/

### Get all books
GET http://localhost:5000/books/

### Get a specific book by ID
GET http://localhost:5000/books/1/details

### Get Genres 
GET http://localhost:5000/genres/

### Get Books by Genre
GET http://localhost:5000/genres/1/
